apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: updownchecks.zentainer.io
spec:
  group: zentainer.io
  version: v1
  names:
    kind: UpDownCheck
    plural: updownchecks
    singular: updowncheck
    shortNames:
    - udc
  scope: Namespaced
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: updowncontroller
spec:
  resyncPeriodSeconds: 60
  generateSelector: true
  parentResource:
    apiVersion: zentainer.io/v1
    resource: updownchecks
  hooks:
    sync:
      webhook:
        url: http://updowncontroller.zt-system/sync
    finalize:
      webhook:
        url: http://updowncontroller.zt-system/finalize
