
---
# Deployment # UPDOWN_API_KEY
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: updowncontroller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: updowncontroller
    spec:
      containers:
      - name: updowncontroller
        command:  [ 'python', 'app.py' ]
        image: 275271710846.dkr.ecr.us-west-2.amazonaws.com/updowncontroller:2018-11-13_14-38-18
        ports:
        - containerPort: 5000
        env:
        - name: "FLASK_APP"
          value: "app.py"
        envFrom:
          - secretRef:
              name: updownapikey
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: updowncontroller
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: updowncontroller
